### ISSUE TITLE
Restoring damaged database "Unable to read header from channel"

### ISSUE THREAD

**Issue by zpbd** [cryptomator/sanitizer#8]
Hi there,

We are using Cryptomator with Google Team Drive, and we have had an unexplained incident where a whole load of files and folders were deleted from someone's machine that was syncing up to Google Team Drive.

The first thing I did was hit "Restore" in the Google Team Drive web UI - this was a massive mistake.

Their restore system didn't care about the order of the restore operations and consequently dumped thousands of files in the root folder of the drive because it had not yet come around to restoring the folders they belong in. The thought had crossed my mind for a second before I hit "Restore", and I dismissed the idea that Google could be so silly as to not restore files to the correct directory...

Long story short, here I am with thousands of encrypted files in the root directory. I've tried running Sanitizer decryptVault, in the hope that it could restore my folders and files (but with missing filenames?? not the worst outcome compared to total data loss), but I keep getting hit with exceptions such as:
 
`2R\D5OLMSUE34KYVE76YH4QXIEARUA6TX\BSQFCT6MDQVZEOTOO62M5WFRT3VRUMFB.lng -> c:\vaultname\decrypted\root\blah\blah\blah\unknown-file.LNG
Exception in thread "main" java.lang.IllegalArgumentException: Unable to read header from channel.`

As I'm desperate (this is a huge data loss) I also tried to find out the directory paths for each file via the Google Drive API so that I could restore the folder structure that way, but that doesn't seem to be possible unless someone [answers my StackOverflow](https://stackoverflow.com/questions/58082724/google-drive-api-recovering-the-original-folder-for-a-file-restored-from-trash) with some magic.

Do you have any advice on what my next steps should be?

**Comment by nondedjeu** [comment]
I used decryptVault on a corrupted vault and it worked well, although the process first also stopped on such exceptions.
I think you should delete all `.lng` files that are < 88 bytes, then decryptVault will not get such errors anymore.
Good luck !

**Comment by zpbd** [comment]
Thanks for that tip @nondedjeu 

After deleting half a dozen `.lng` files with double digit byte lengths, the `decryptVault` command did run to completion.

Does anyone know if it's possible to recover any folder structure? Where should I be putting the orphaned `.lng` and extensionless `d` files? The only way I was able to spit out the decrypted orphaned files was to put them in one of the `d` folders randomly, but that meant of course that all of the decrypted files appeared in that one folder.

If anyone knows outright wether it is technically possible to recover the folders so that all of my `unknown-file-xx` files are in the correct named folders, it would be great to clarify that. But based on my brief skim of the Cryptomator docs I'm guessing this is impossible.

**Comment by overheadhunter** [comment]
To add a little explanation:

Since your directory structure got destroyed but all files are still present, you'll end up with two types of `.lng` files:

- Those, that have been inside the `d` directory and that contain actual data.
- Those inside the `m` directory, that contain only the file name

Since all your files ended up in the same directory, you have some files that contain names instead of data but sanitizer tries to decrypt the data (which failed with the above-mentioned exception).

> If anyone knows outright wether it is technically possible to recover the folders so that all of my `unknown-file-xx` files are in the correct named folders, it would be great to clarify that. But based on my brief skim of the Cryptomator docs I'm guessing this is impossible.

Without the directory structure your filenames are doomed. This is because filenames are cryptographically bound to their parent directory to prohibit an attacker from moving files inside the encrypted structure.

**Comment by zpbd** [comment]
Thanks for the clarification.

So I guess this is as good as it gets - 3000 unnamed files in the same directory, correct?

`This is because filenames are cryptographically bound to their parent directory to prohibit an attacker from moving files inside the encrypted structure.`

I don't really follow that attack. What would the attacker achieve by moving your files around?

**Comment by overheadhunter** [comment]
> I don't really follow that attack. What would the attacker achieve by moving your files around?

For example he could trick you into accidentally exposing your files. Say the attacker has access to your cloud storage and can see the modification date of encrypted files. Then he knows what you're currently working on. Maybe he also knows that you eventually publish work from inside your vault as soon as it's finished, so he might try to move recently-edited files to some older dir in the hope that this dir is among the candidates to be published next.

That said, there are other attacks like cryptomator/cryptomator#119 that effectively allow the same kind of attack.

Still there are further reasons for having the filename bound to the directory, such as not revealing repeating patterns among directory contents. So an attacker can not see if you have identically named files inside different directories.

**Comment by zpbd** [comment]
Makes sense.

We managed to recover our data using the G Suite Admin SDK Reporting API which can give information about the previous parent of a drive file that has been restored and orphaned. So with that and the Google Drive API you can re-parent all of the files correctly, and it all opened up in Cryptomator beautifully.

If anyone is ever in a similar situation coming from Google Team Drive, I've posted the [question](https://stackoverflow.com/questions/58082724/google-drive-api-recovering-the-original-folder-for-a-file-restored-from-trash) and [solution](https://github.com/zpbd/GoogleDriveOrphanedFileRestorer) on StackOverflow and GitHub.

**Comment by overheadhunter** [comment]
Wow, kudos to you for publishing the restorer!
